"""Tests for the command line interface, including exit codes."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from spatial_index_advisor import cli
from spatial_index_advisor.cli import EXIT_ERROR, EXIT_FINDINGS, EXIT_OK, main

from .test_collector import FakeConnection, catalog_rows


def run(capsys, *argv: str) -> tuple[int, str, str]:
    """Invoke the CLI and capture its streams."""
    code = main(list(argv))
    captured = capsys.readouterr()
    return code, captured.out, captured.err


def test_rich_report_is_the_default(capsys, examples_dir: Path) -> None:
    code, out, _ = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "pg_stat_statements.csv"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--no-color",
    )
    assert code == EXIT_FINDINGS
    assert "Spatial index recommendations" in out


def test_json_output_is_machine_readable(capsys, examples_dir: Path) -> None:
    code, out, _ = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--format",
        "json",
    )
    payload = json.loads(out)
    assert code == EXIT_FINDINGS
    assert payload["recommendations"]


def test_sql_output_can_be_piped_to_psql(capsys, examples_dir: Path) -> None:
    _, out, _ = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--format",
        "sql",
    )
    assert out.startswith("-- Generated by spatial-index-advisor.")
    assert "CREATE INDEX CONCURRENTLY" in out


def test_top_limits_the_output(capsys, examples_dir: Path) -> None:
    _, out, _ = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "pg_stat_statements.csv"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--format",
        "json",
        "--top",
        "3",
    )
    assert len(json.loads(out)["recommendations"]) == 3


def test_top_must_be_positive(capsys, examples_dir: Path) -> None:
    code, _, err = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--top",
        "0",
    )
    assert code == EXIT_ERROR
    assert "--top must be at least 1" in err


def test_fail_on_never_always_succeeds(capsys, examples_dir: Path) -> None:
    code, _, _ = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--format",
        "json",
        "--fail-on",
        "never",
    )
    assert code == EXIT_OK


def test_clean_workload_exits_zero(capsys, tmp_path: Path) -> None:
    catalog = tmp_path / "catalog.json"
    catalog.write_text(
        json.dumps(
            {
                "tables": [
                    {
                        "name": "public.t",
                        "row_count": 100,
                        "table_bytes": 8192,
                        "geometry_columns": [{"name": "geom", "geometry_type": "POINT"}],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    workload = tmp_path / "q.sql"
    workload.write_text("SELECT 1 FROM t WHERE ST_Intersects(geom, $1);", encoding="utf-8")
    code, out, _ = run(capsys, "analyze", "-w", str(workload), "-c", str(catalog), "--no-color")
    assert code == EXIT_OK
    assert "No recommendations" in out


def test_missing_workload_file_is_a_clean_error(capsys, examples_dir: Path) -> None:
    code, _, err = run(
        capsys,
        "analyze",
        "-w",
        "/nonexistent/workload.csv",
        "-c",
        str(examples_dir / "catalog.json"),
    )
    assert code == EXIT_ERROR
    assert "does not exist" in err


def test_missing_catalog_file_is_a_clean_error(capsys, examples_dir: Path) -> None:
    code, _, err = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        "/nonexistent/catalog.json",
    )
    assert code == EXIT_ERROR
    assert "does not exist" in err


def test_forced_workload_format_is_honoured(capsys, examples_dir: Path) -> None:
    code, _, err = run(
        capsys,
        "analyze",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--workload-format",
        "csvlog",
    )
    assert code == EXIT_ERROR
    assert "does not look like PostgreSQL csvlog" in err


def test_analyse_alias_works(capsys, examples_dir: Path) -> None:
    code, _, _ = run(
        capsys,
        "analyse",
        "-w",
        str(examples_dir / "queries.sql"),
        "-c",
        str(examples_dir / "catalog.json"),
        "--format",
        "json",
    )
    assert code == EXIT_FINDINGS


def test_version_flag_exits_cleanly() -> None:
    with pytest.raises(SystemExit) as excinfo:
        main(["--version"])
    assert excinfo.value.code == 0


def test_missing_subcommand_is_a_usage_error() -> None:
    with pytest.raises(SystemExit) as excinfo:
        main([])
    assert excinfo.value.code != 0


# --------------------------------------------------------------------------- #
# collect
# --------------------------------------------------------------------------- #


def test_collect_writes_a_snapshot_to_stdout(capsys, monkeypatch) -> None:
    monkeypatch.setattr(cli, "connect", lambda dsn: FakeConnection(catalog_rows()))
    code, out, _ = run(capsys, "collect", "--dsn", "postgresql:///fleet")
    payload = json.loads(out)
    assert code == EXIT_OK
    assert payload["tables"][0]["name"] == "public.pings"


def test_collect_writes_a_snapshot_to_a_file(capsys, monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(cli, "connect", lambda dsn: FakeConnection(catalog_rows()))
    target = tmp_path / "catalog.json"
    code, _, err = run(
        capsys, "collect", "--dsn", "postgresql:///fleet", "--output", str(target)
    )
    assert code == EXIT_OK
    assert "Wrote snapshot" in err
    assert json.loads(target.read_text(encoding="utf-8"))["tables"]


def test_collect_reports_an_unwritable_output_path(capsys, monkeypatch) -> None:
    monkeypatch.setattr(cli, "connect", lambda dsn: FakeConnection(catalog_rows()))
    code, _, err = run(
        capsys, "collect", "--dsn", "postgresql:///fleet", "-o", "/nonexistent/dir/out.json"
    )
    assert code == EXIT_ERROR
    assert "cannot write" in err


def test_collect_surfaces_connection_failures(capsys, monkeypatch) -> None:
    from spatial_index_advisor.errors import CollectorError

    def explode(dsn: str):
        raise CollectorError("cannot connect to the database: no route to host")

    monkeypatch.setattr(cli, "connect", explode)
    code, _, err = run(capsys, "collect", "--dsn", "postgresql:///nope")
    assert code == EXIT_ERROR
    assert "no route to host" in err
